/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ComboboxAnchor: typeof import('reka-ui')['ComboboxAnchor']
    ComboboxContent: typeof import('reka-ui')['ComboboxContent']
    ComboboxEmpty: typeof import('reka-ui')['ComboboxEmpty']
    ComboboxGroup: typeof import('reka-ui')['ComboboxGroup']
    ComboboxInput: typeof import('reka-ui')['ComboboxInput']
    ComboboxItem: typeof import('reka-ui')['ComboboxItem']
    ComboboxItemIndicator: typeof import('reka-ui')['ComboboxItemIndicator']
    ComboboxLabel: typeof import('reka-ui')['ComboboxLabel']
    ComboboxRoot: typeof import('reka-ui')['ComboboxRoot']
    ComboboxSeparator: typeof import('reka-ui')['ComboboxSeparator']
    ComboboxTrigger: typeof import('reka-ui')['ComboboxTrigger']
    ComboboxViewport: typeof import('reka-ui')['ComboboxViewport']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0_@babel+parser@7.26.10_embla-carousel@8.5.2_typescript@5.8.2_vite@6.2.2_jiti@2._jqcqix7ircpev4xsasnrtllx6a/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UAvatar: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0_@babel+parser@7.26.10_embla-carousel@8.5.2_typescript@5.8.2_vite@6.2.2_jiti@2._jqcqix7ircpev4xsasnrtllx6a/node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue')['default']
    ULinkBase: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0_@babel+parser@7.26.10_embla-carousel@8.5.2_typescript@5.8.2_vite@6.2.2_jiti@2._jqcqix7ircpev4xsasnrtllx6a/node_modules/@nuxt/ui/dist/runtime/components/LinkBase.vue')['default']
  }
}
